/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockACLInterface extends Interface {
  getFunction(
    nameOrSignature: "allow" | "allowTransient" | "isAllowed" | "persistAllowed"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Allowed"): EventFragment;

  encodeFunctionData(
    functionFragment: "allow",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowTransient",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "persistAllowed",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "allow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowTransient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAllowed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "persistAllowed",
    data: BytesLike
  ): Result;
}

export namespace AllowedEvent {
  export type InputTuple = [account: AddressLike, handle: BigNumberish];
  export type OutputTuple = [account: string, handle: bigint];
  export interface OutputObject {
    account: string;
    handle: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockACL extends BaseContract {
  connect(runner?: ContractRunner | null): MockACL;
  waitForDeployment(): Promise<this>;

  interface: MockACLInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allow: TypedContractMethod<
    [handle: BigNumberish, account: AddressLike],
    [void],
    "nonpayable"
  >;

  allowTransient: TypedContractMethod<
    [handle: BigNumberish, account: AddressLike],
    [void],
    "nonpayable"
  >;

  isAllowed: TypedContractMethod<
    [handle: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;

  persistAllowed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allow"
  ): TypedContractMethod<
    [handle: BigNumberish, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowTransient"
  ): TypedContractMethod<
    [handle: BigNumberish, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isAllowed"
  ): TypedContractMethod<
    [handle: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "persistAllowed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "Allowed"
  ): TypedContractEvent<
    AllowedEvent.InputTuple,
    AllowedEvent.OutputTuple,
    AllowedEvent.OutputObject
  >;

  filters: {
    "Allowed(address,uint256)": TypedContractEvent<
      AllowedEvent.InputTuple,
      AllowedEvent.OutputTuple,
      AllowedEvent.OutputObject
    >;
    Allowed: TypedContractEvent<
      AllowedEvent.InputTuple,
      AllowedEvent.OutputTuple,
      AllowedEvent.OutputObject
    >;
  };
}
