/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockInputVerifierInterface extends Interface {
  getFunction(
    nameOrSignature: "verifyCiphertext" | "verifyInputProof"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "InputVerified"): EventFragment;

  encodeFunctionData(
    functionFragment: "verifyCiphertext",
    values: [BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyInputProof",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "verifyCiphertext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyInputProof",
    data: BytesLike
  ): Result;
}

export namespace InputVerifiedEvent {
  export type InputTuple = [sender: AddressLike, proofHash: BytesLike];
  export type OutputTuple = [sender: string, proofHash: string];
  export interface OutputObject {
    sender: string;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockInputVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): MockInputVerifier;
  waitForDeployment(): Promise<this>;

  interface: MockInputVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  verifyCiphertext: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike, arg2: AddressLike],
    [boolean],
    "view"
  >;

  verifyInputProof: TypedContractMethod<
    [inputProof: BytesLike, sender: AddressLike],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "verifyCiphertext"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike, arg2: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyInputProof"
  ): TypedContractMethod<
    [inputProof: BytesLike, sender: AddressLike],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "InputVerified"
  ): TypedContractEvent<
    InputVerifiedEvent.InputTuple,
    InputVerifiedEvent.OutputTuple,
    InputVerifiedEvent.OutputObject
  >;

  filters: {
    "InputVerified(address,bytes32)": TypedContractEvent<
      InputVerifiedEvent.InputTuple,
      InputVerifiedEvent.OutputTuple,
      InputVerifiedEvent.OutputObject
    >;
    InputVerified: TypedContractEvent<
      InputVerifiedEvent.InputTuple,
      InputVerifiedEvent.OutputTuple,
      InputVerifiedEvent.OutputObject
    >;
  };
}
