/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockInputVerifier,
  MockInputVerifierInterface,
} from "../../../contracts/mocks/MockInputVerifier";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "proofHash",
        type: "bytes32",
      },
    ],
    name: "InputVerified",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "verifyCiphertext",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "inputProof",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "verifyInputProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b506102858061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c806336eddace14610038578063615780ac1461005f575b5f5ffd5b61004b610046366004610190565b610076565b604051901515815260200160405180910390f35b61004b61006d3660046101db565b60019392505050565b815160208301206040515f919073ffffffffffffffffffffffffffffffffffffffff8416907fb1cb9531d8d206f94754c9a0d7fc1ebf2a7fcffee1c3b4d34600cd5eb7e9dba8908490a350600192915050565b634e487b7160e01b5f52604160045260245ffd5b5f82601f8301126100ec575f5ffd5b813567ffffffffffffffff811115610106576101066100c9565b604051601f8201601f19908116603f0116810167ffffffffffffffff81118282101715610135576101356100c9565b60405281815283820160200185101561014c575f5ffd5b816020850160208301375f918101602001919091529392505050565b803573ffffffffffffffffffffffffffffffffffffffff8116811461018b575f5ffd5b919050565b5f5f604083850312156101a1575f5ffd5b823567ffffffffffffffff8111156101b7575f5ffd5b6101c3858286016100dd565b9250506101d260208401610168565b90509250929050565b5f5f5f606084860312156101ed575f5ffd5b833567ffffffffffffffff811115610203575f5ffd5b61020f868287016100dd565b935050602084013567ffffffffffffffff81111561022b575f5ffd5b610237868287016100dd565b92505061024660408501610168565b9050925092509256fea2646970667358221220abef3665403a4e75bb2d98478ccec1ee94e07b4c14987f1ac23f052d0677f56e64736f6c634300081b0033";

type MockInputVerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockInputVerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockInputVerifier__factory extends ContractFactory {
  constructor(...args: MockInputVerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockInputVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockInputVerifier__factory {
    return super.connect(runner) as MockInputVerifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockInputVerifierInterface {
    return new Interface(_abi) as MockInputVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockInputVerifier {
    return new Contract(address, _abi, runner) as unknown as MockInputVerifier;
  }
}
