/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockACL,
  MockACLInterface,
} from "../../../contracts/mocks/MockACL";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "handle",
        type: "uint256",
      },
    ],
    name: "Allowed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "handle",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "allow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "handle",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "allowTransient",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "handle",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isAllowed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "persistAllowed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b506101ad8061001c5f395ff3fe608060405234801561000f575f5ffd5b506004361061004a575f3560e01c806337e6b44f1461004e5780635faa299a1461007857806365d0509c146100b85780638d9c9c92146100b8575b5f5ffd5b61006461005c366004610131565b600192915050565b604051901515815260200160405180910390f35b610064610086366004610131565b73ffffffffffffffffffffffffffffffffffffffff165f90815260208181526040808320938352929052205460ff1690565b6100cb6100c6366004610131565b6100cd565b005b73ffffffffffffffffffffffffffffffffffffffff81165f81815260208181526040808320868452909152808220805460ff19166001179055518492917f9f6a9982e68048113ec7fb2b76a7ee454217214be376ad9da8393eb4ef774d4b91a35050565b5f5f60408385031215610142575f5ffd5b82359150602083013573ffffffffffffffffffffffffffffffffffffffff8116811461016c575f5ffd5b80915050925092905056fea26469706673582212203bf312d6c8a54d566ae0e3c6605285a47316f501ca84314dbae661268e067c0e64736f6c634300081b0033";

type MockACLConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockACLConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockACL__factory extends ContractFactory {
  constructor(...args: MockACLConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockACL & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockACL__factory {
    return super.connect(runner) as MockACL__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockACLInterface {
    return new Interface(_abi) as MockACLInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockACL {
    return new Contract(address, _abi, runner) as unknown as MockACL;
  }
}
