/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SatisfactionSurveyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowUserToDecrypt"
      | "decryptManager"
      | "getDepartmentAggregates"
      | "getGlobalAggregates"
      | "protocolId"
      | "submitResponse"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "allowUserToDecrypt",
    values: [AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "decryptManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDepartmentAggregates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalAggregates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitResponse",
    values: [BytesLike, BytesLike, BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowUserToDecrypt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepartmentAggregates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalAggregates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitResponse",
    data: BytesLike
  ): Result;
}

export interface SatisfactionSurvey extends BaseContract {
  connect(runner?: ContractRunner | null): SatisfactionSurvey;
  waitForDeployment(): Promise<this>;

  interface: SatisfactionSurveyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowUserToDecrypt: TypedContractMethod<
    [user: AddressLike, deptIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  decryptManager: TypedContractMethod<[], [string], "view">;

  getDepartmentAggregates: TypedContractMethod<
    [deptId: BigNumberish],
    [[string, string] & { total: string; count: string }],
    "view"
  >;

  getGlobalAggregates: TypedContractMethod<
    [],
    [[string, string] & { total: string; count: string }],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  submitResponse: TypedContractMethod<
    [
      encScore: BytesLike,
      scoreProof: BytesLike,
      deptId: BigNumberish,
      encOne: BytesLike,
      oneProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowUserToDecrypt"
  ): TypedContractMethod<
    [user: AddressLike, deptIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decryptManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDepartmentAggregates"
  ): TypedContractMethod<
    [deptId: BigNumberish],
    [[string, string] & { total: string; count: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGlobalAggregates"
  ): TypedContractMethod<
    [],
    [[string, string] & { total: string; count: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitResponse"
  ): TypedContractMethod<
    [
      encScore: BytesLike,
      scoreProof: BytesLike,
      deptId: BigNumberish,
      encOne: BytesLike,
      oneProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
